spring.application.name=demo
server.port=8081

# Base de datos H2 en archivo (persiste entre reinicios)
spring.datasource.url=jdbc:h2:file:/home/desarrollo/biblioteca-proyecto-integrador-2026/app/data/bibliotecadb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Thymeleaf
spring.thymeleaf.cache=false
